{
  "id": "uno-ooo-parser",
  "version": "0.1.16",
  "libre_office_ver": "7.2",
  "name": "UndoContextNotClosedException",
  "type": "exception",
  "namespace": "com.sun.star.document",
  "parser_args": {
    "sort": true,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        "..util.invalid_state_exception",
        "InvalidStateException",
        "util_invalid_state_exception_i"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.util.InvalidStateException": "util_invalid_state_exception_i"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "UndoContextNotClosedException",
    "namespace": "com.sun.star.document",
    "imports": [],
    "extends": [
      "com.sun.star.util.InvalidStateException"
    ],
    "desc": [
      "is thrown when an operation is attempted at an XUndoManager which requires all undo contexts to be closed, but this requirement is not fulfilled.",
      "",
      "**since**",
      "",
      "    OOo 3.4"
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1document_1_1UndoContextNotClosedException.html",
    "items": {}
  }
}