{
  "id": "uno-ooo-parser",
  "version": "0.1.32",
  "libre_office_ver": "7.2",
  "name": "ScannerException",
  "type": "exception",
  "namespace": "com.sun.star.scanner",
  "parser_args": {
    "sort": false,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "allow_db": true,
    "from_imports": [
      [
        "..uno.exception",
        "Exception",
        "Exception_85530a09"
      ]
    ],
    "from_imports_typing": [
      [
        ".scan_error",
        "ScanError",
        "ScanError_b0d90b81"
      ]
    ],
    "extends_map": {
      "com.sun.star.uno.Exception": "Exception_85530a09"
    },
    "quote": [
      "ScanError_b0d90b81"
    ],
    "typings": [],
    "requires_typing": true,
    "full_imports": {
      "general": [
        "com.sun.star.uno.Exception"
      ],
      "typing": [
        "com.sun.star.scanner.ScanError"
      ]
    },
    "imports": [],
    "name": "ScannerException",
    "namespace": "com.sun.star.scanner",
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "A ScannerException gets thrown if an object of type XScannerManager could not complete a specific action."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1scanner_1_1ScannerException.html",
    "items": {
      "properties": [
        {
          "name": "Error",
          "returns": "ScanError_b0d90b81",
          "origtype": "com.sun.star.scanner.ScanError",
          "origin": "com.sun.star.scanner.ScanError",
          "desc": [
            "Error: contains the specific reason for failure."
          ],
          "raises_get": "",
          "raises_set": ""
        }
      ]
    }
  }
}