{
  "id": "uno-ooo-parser",
  "version": "0.2.9",
  "libre_office_ver": "7.3",
  "name": "ConnectException",
  "type": "exception",
  "namespace": "com.sun.star.io",
  "parser_args": {
    "sort": false,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "allow_db": true,
    "from_imports": [
      [
        ".socket_exception",
        "SocketException",
        "SocketException_bb650bf8"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.io.SocketException": "SocketException_bb650bf8"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "full_imports": {
      "general": [
        "com.sun.star.io.SocketException"
      ],
      "typing": []
    },
    "imports": [],
    "name": "ConnectException",
    "namespace": "com.sun.star.io",
    "extends": [
      "com.sun.star.io.SocketException"
    ],
    "desc": [
      "Signals that an error occurred while attempting to connect a socket to a remote address and port.",
      "",
      "Typically, the connection was refused remotely (e.g., no process is listening on the remote address/port)."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1io_1_1ConnectException.html",
    "items": {}
  }
}