{
  "id": "uno-ooo-parser",
  "version": "0.1.17",
  "libre_office_ver": "7.2",
  "name": "AlreadyConnectedException",
  "type": "exception",
  "namespace": "com.sun.star.io",
  "parser_args": {
    "sort": true,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        ".io_exception",
        "IOException",
        "io_exception_i"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.io.IOException": "io_exception_i"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "AlreadyConnectedException",
    "namespace": "com.sun.star.io",
    "imports": [],
    "extends": [
      "com.sun.star.io.IOException"
    ],
    "desc": [
      "is thrown when a client tries to connect to a resource to which he is already connected."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1io_1_1AlreadyConnectedException.html",
    "items": {}
  }
}