{
  "id": "uno-ooo-parser",
  "version": "0.1.18",
  "libre_office_ver": "7.2",
  "name": "ConnectException",
  "type": "exception",
  "namespace": "com.sun.star.io",
  "parser_args": {
    "sort": true,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        ".socket_exception",
        "SocketException",
        "socket_exception_i"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.io.SocketException": "socket_exception_i"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "full_imports": {
      "general": [
        "com.sun.star.io.SocketException"
      ],
      "typing": []
    },
    "name": "ConnectException",
    "imports": [],
    "namespace": "com.sun.star.io",
    "extends": [
      "com.sun.star.io.SocketException"
    ],
    "desc": [
      "Signals that an error occurred while attempting to connect a socket to a remote address and port.",
      "",
      "Typically, the connection was refused remotely (e.g., no process is listening on the remote address/port)."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1io_1_1ConnectException.html",
    "items": {}
  }
}