{
  "id": "uno-ooo-parser",
  "version": "0.1.15",
  "libre_office_ver": "7.2",
  "name": "AuthenticationFallbackRequest",
  "type": "exception",
  "namespace": "com.sun.star.ucb",
  "parser_args": {
    "sort": true,
    "long_names": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        "..task.classified_interaction_request",
        "ClassifiedInteractionRequest",
        "task_classified_interaction_request_i"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.task.ClassifiedInteractionRequest": "task_classified_interaction_request_i"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "AuthenticationFallbackRequest",
    "namespace": "com.sun.star.ucb",
    "imports": [],
    "extends": [
      "com.sun.star.task.ClassifiedInteractionRequest"
    ],
    "desc": [
      "An interaction continuation handing back some authentication data.",
      "",
      "**since**",
      "",
      "    LibreOffice 4.4"
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1ucb_1_1AuthenticationFallbackRequest.html",
    "items": {
      "properties": [
        {
          "name": "instructions",
          "returns": "str",
          "desc": [
            "Instructions to be followed by the user."
          ],
          "raises_get": "",
          "raises_set": ""
        },
        {
          "name": "url",
          "returns": "str",
          "desc": [
            "url to be opened in browser"
          ],
          "raises_get": "",
          "raises_set": ""
        }
      ]
    }
  }
}