{
  "id": "uno-ooo-parser",
  "version": "0.1.16",
  "libre_office_ver": "7.2",
  "name": "CommandAbortedException",
  "type": "exception",
  "namespace": "com.sun.star.ucb",
  "parser_args": {
    "sort": true,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        "..uno.exception",
        "Exception",
        "uno_exception_i"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.uno.Exception": "uno_exception_i"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "CommandAbortedException",
    "namespace": "com.sun.star.ucb",
    "imports": [],
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "This exception is thrown to indicate that a command was aborted."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1ucb_1_1CommandAbortedException.html",
    "items": {}
  }
}