{
  "id": "uno-ooo-parser",
  "version": "0.1.16",
  "libre_office_ver": "7.2",
  "name": "InteractiveNetworkGeneralException",
  "type": "exception",
  "namespace": "com.sun.star.ucb",
  "parser_args": {
    "sort": true,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        ".interactive_network_exception",
        "InteractiveNetworkException",
        "interactive_network_exception_i"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.ucb.InteractiveNetworkException": "interactive_network_exception_i"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "InteractiveNetworkGeneralException",
    "namespace": "com.sun.star.ucb",
    "imports": [],
    "extends": [
      "com.sun.star.ucb.InteractiveNetworkException"
    ],
    "desc": [
      "A network error specifying a general failure."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1ucb_1_1InteractiveNetworkGeneralException.html",
    "items": {}
  }
}