{
  "id": "uno-ooo-parser",
  "version": "0.1.12",
  "timestamp": "2022-01-04 18:58:38+00:00",
  "name": "InteractiveNetworkConnectException",
  "type": "exception",
  "namespace": "com.sun.star.ucb",
  "parser_args": {
    "sort": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        ".interactive_network_exception",
        "InteractiveNetworkException"
      ]
    ],
    "from_imports_typing": [],
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "InteractiveNetworkConnectException",
    "namespace": "com.sun.star.ucb",
    "imports": [],
    "extends": [
      "com.sun.star.ucb.InteractiveNetworkException"
    ],
    "desc": [
      "A network error specifying a connection failure."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1ucb_1_1InteractiveNetworkConnectException.html",
    "items": {
      "properties": [
        {
          "name": "Server",
          "returns": "str",
          "desc": [
            "The name of the server to which connecting failed."
          ],
          "raises_get": "",
          "raises_set": ""
        }
      ]
    }
  }
}