{
  "id": "uno-ooo-parser",
  "version": "0.1.8",
  "timestamp": "2021-12-28 10:14:19+00:00",
  "name": "LdapGenericException",
  "type": "exception",
  "namespace": "com.sun.star.ldap",
  "parser_args": {
    "sort": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        "..uno.exception",
        "Exception"
      ]
    ],
    "from_imports_typing": [],
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "name": "LdapGenericException",
    "namespace": "com.sun.star.ldap",
    "imports": [],
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "Generic exception occurring during access to an LDAP server.",
      "",
      "The actual LDAP error code is provided for more refined error management.",
      "",
      "**since**",
      "",
      "    OOo 1.1.2"
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1ldap_1_1LdapGenericException.html",
    "items": {
      "properties": [
        {
          "name": "ErrorCode",
          "returns": "int",
          "desc": [
            "LDAP error code, see LDAP SDK documentation for complete list of possible values and their meaning."
          ],
          "raises_get": "",
          "raises_set": ""
        }
      ]
    }
  }
}